name: E2E tests for dev servers
on:
  workflow_dispatch:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
	strategy:
	  matrix: framework: [angular, react, vue]
    with:
      node-version: 18.x
    steps:
	  - name: Checkout
	    uses: actions/checkout@v2

	  - name: Install dependencies
	    run: npm ci

	  - name: Install framework
	    run: npm install ${{ matrix.framework }}

	  - name: Run test
      uses: cypress-io/github-action@v2
        with:
          start: npm run e2e:static
          wait-on: "http://0.0.0.0:1234, http://localhost:7071"
          wait-on-timeout: 120
          run: npm run e2e:${{ matrix.framework }}:test
